language: java

jdk:
  - openjdk14

sudo: false

services:
  - postgresql

before_install:
  - psql -c 'create database schema;' -U postgres

env:
  global:
    - CODECOV_TOKEN="7b2ec175-1dee-4ecd-8214-17784dce9305"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - Nefedova.Katia@yandex.ru
    on_success: never # default: change
    on_failure: never # default: always